title: "Coralsundy: Mod/Subtitle/Review"
author: Coralsundy
subtitle: Coralsundy's Home Page

url: "https://coralsundy.com"
baseurl: "/"

footer_only_homepage: true
footer_url_github: "https://github.com/coralsundy"
footer_text_github: "Github"
footer_url_twitter: "https://twitter.com/coralsundy"
footer_text_twitter: "Twitter"
footer_url_email: "mailto:coralsundy@gmail.com"
footer_text_email: "Email"
footer_url_license: "https://github.com/coralsundy/coralsundy-website/blob/main/LICENSE.md"
footer_text_license: "License"

#profile-picture: assets/profile.jpg
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

encoding: utf-8

timezone: "America/Los_Angeles"

exclude:
- _examples
- _drafts

navbar:
 - name: "About"
   link: "about"
 - name: "Links"
   link: "links"
 - name: "Tags"
   link: "tags"

plugins:
- jemoji
- jekyll-sitemap

