title: "Coralsundy: Mod/Subtitle/Review"
author: Coralsundy
subtitle: Coralsundy's Home Page

url: "https://coralsundy.com"
baseurl: "/"

footer_only_homepage: true
footer_url_github: "https://github.com/coralsundy"
footer_text_github: "Github"
footer_url_twitter: "https://twitter.com/coralsundy"
footer_text_twitter: "Twitter"
footer_url_weibo: "https://weibo.com/n/coralsundy"
footer_text_weibo: "Weibo"
footer_url_email: "mailto:coralsundy@gmail.com"
footer_text_email: "Email"
footer_url_license: "https://github.com/coralsundy/coralsundy-website/blob/main/LICENSE.md"
footer_text_license: "License"
footer_url_rss_xml: "/feed.xml"
footer_text_rss_xml: "RSS(xml)"
footer_url_rss_json: "/feed.json"
footer_text_rss_json: "RSS(json)"

#profile-picture: assets/profile.jpg
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

encoding: utf-8

#github: [metadata]
#export JEKYLL_GITHUB_TOKEN=<PAT> to remove the github auth metadata warning

timezone: "America/Los_Angeles"

future: true

exclude:
- _examples
- _drafts

navbar:
 - name: "About"
   link: "about"
 - name: "Links"
   link: "links"
 - name: "Tags"
   link: "tags"

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-feed

