title: "Coralsundy: Mod/Subtitle/Review"
author: Coralsundy
subtitle: Coralsundy's Home Page

url: "https://coralsundy.com"
baseurl: "/"

footer_only_homepage: true
footer_url: "https://github.com/coralsundy"
footer_text: "Coralsundy GitHub Account"

#profile-picture: assets/profile.jpg
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

exclude:
- _example

navbar:
 - name: "About"
   link: "about"
 - name: "Links"
   link: "links"
 - name: "Tags"
   link: "tags"

plugins:
- jemoji

